[package]
name = "axochat"
version = "0.10.0"
authors = ["frozolotl <frozolotl@protonmail.com>"]
edition = "2018"
license = "MIT"

[features]
default = ["rustls-tls"]
rustls-tls = ["dep:rustls", "actix-web/rustls-0_23"]
openssl-tls = ["dep:openssl", "actix-web/openssl"]

[dependencies]
log = "0.4"
env_logger = "0.11"
clap = { version = "4.6", features = ["derive", "env"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
humantime = "2.4"
rand = { version = "0.10", default-features = false, features = ["sys_rng"] }
rand_hc = "0.5"
uuid = { version = "1.27", features = ["serde"] }
snafu = "0.9"

actix-web = { version = "4.15", default-features = false, features = ["macros"] }
actix-ws = "0.4"
actix = "0.13"

jsonwebtoken = { version = "11.1", features = ["aws_lc_rs"] }

rustls = { version = "0.23", optional = true }
openssl = { version = "0.10", features = ["v110"], optional = true }

url = "2.5"
reqwest = { version = "0.13", default-features = false, features = ["json", "rustls"] }
rlimit = "0.11"
